# Uncomment this line to define a global platform for your project
 platform :ios, '9.0'
 use_frameworks!

target 'BlackNotes' do

end

target 'BlackNotesTests' do

end

target 'BlackNotesShareExt' do
pod 'Firebase', '>= 2.4.0'
end

